spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/test
    username: postgres
    password: 19990227
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql